"""
WP17: CRLS Synthesis Closure
=============================

Closes the fourth quadrant of the CRLS Strange Loop so that the correction
generated by the meta-level actually mutates the object-level MetaLearner,
and the subsequent generation's accuracy confirms the causal effect.

The gap in v0.114
-----------------
``SelfCorrectionEngine.apply_correction()`` returns a modified dict that nothing
reads; the MetaLearner is never touched.  The loop *observes* and *generates*
but never *synthesises* — Hofstadter's fourth beat is missing.

WP17 fix
--------
``CRLSSynthesiser`` holds a live reference to the ``MetaLearner`` and executes
four concrete synthesis actions that directly mutate strategy probabilities:

  DEMOTE_WORST   – halve the probability of the worst-performing strategy
  PROMOTE_BEST   – double the probability of the best-performing strategy
  RESET_UNIFORM  – reset to uniform prior (escape local optima)
  BOOST_UPWARD   – increase the upward mutation rate itself (meta-meta level)

The key to distinguishing CRLS synthesis from the MetaLearner's own autonomous
updates: the test harness sets ``upward_rate = downward_rate = 0`` (frozen
autonomous updates) and relies entirely on the CRLS loop for learning.  Any
accuracy improvement in generation N+1 is therefore causally attributable to
the synthesis action taken at the end of generation N.

Theoretical grounding
---------------------
Hofstadter (GEB, 1979): "In a strange loop … we unexpectedly find ourselves
back where we started."  The loop closes here: the meta-level's correction
changes the MetaLearner whose outputs the meta-level will observe next.

Good (1965): "An ultraintelligent machine … could design even better machines."
The BOOST_UPWARD action demonstrates meta-meta-learning — the machine improves
its own improvement rate.

Classes
-------
SynthesisAction     Enum of the four concrete synthesis operations
SynthesisRecord     Dataclass: one synthesis event (action, before/after probs,
                    generation, safety status)
CRLSSynthesiser     The synthesis engine: takes MetaLearner + pattern summary,
                    proposes a safe action, applies it, records the event
GoTacticalCRLS      Full CRLS loop wired to 9×9 Go tactical puzzles, using the
                    real GoBoard and the existing MetaLearner / MetaCognitionLayer
"""

from __future__ import annotations

import copy
import logging
import math
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple

from prometheus.meta_learner import MetaLearner
from prometheus.v0_114_crls_strange_loop import (
    CorrectionStrategy,
    FailureEpisode,
    FailureType,
    MetaCognitionLayer,
    SelfCorrectionEngine,
)
from prometheus.safety.checks import GodelianSafetyGovernor, SafetyStatus

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Synthesis vocabulary
# ---------------------------------------------------------------------------

class SynthesisAction(Enum):
    """The four concrete actions the CRLS loop can take on the MetaLearner."""
    DEMOTE_WORST  = "demote_worst"   # halve prob of worst strategy
    PROMOTE_BEST  = "promote_best"   # double prob of best strategy
    RESET_UNIFORM = "reset_uniform"  # back to equal priors (escape optima)
    BOOST_UPWARD  = "boost_upward"   # increase upward_rate (meta-meta learning)
    NO_ACTION     = "no_action"      # accuracy stable — do nothing


@dataclass
class SynthesisRecord:
    """Full audit trail for one synthesis event."""
    generation:      int
    action:          SynthesisAction
    trigger:         str              # human-readable reason
    before_probs:    Dict[str, float]
    after_probs:     Dict[str, float]
    before_upward:   float
    after_upward:    float
    safety_status:   str
    safety_reason:   str
    acc_before:      float            # generation N accuracy
    acc_after:       Optional[float] = None  # generation N+1 (filled later)
    improvement:     Optional[float] = None  # acc_after - acc_before
    timestamp:       float = field(default_factory=time.time)

    def causal_confirmed(self) -> bool:
        """True if accuracy improved after the synthesis action."""
        return self.improvement is not None and self.improvement > 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "generation":    self.generation,
            "action":        self.action.value,
            "trigger":       self.trigger,
            "before_probs":  self.before_probs,
            "after_probs":   self.after_probs,
            "before_upward": self.before_upward,
            "after_upward":  self.after_upward,
            "safety_status": self.safety_status,
            "safety_reason": self.safety_reason,
            "acc_before":    self.acc_before,
            "acc_after":     self.acc_after,
            "improvement":   self.improvement,
            "causal_confirmed": self.causal_confirmed(),
        }


# ---------------------------------------------------------------------------
# CRLSSynthesiser
# ---------------------------------------------------------------------------

class CRLSSynthesiser:
    """
    Closes the CRLS loop by directly mutating the MetaLearner.

    Responsibilities
    ----------------
    1. Receive the pattern summary from MetaCognitionLayer (Critique phase output)
    2. Choose a synthesis action based on failure diagnosis (Revise phase)
    3. Gate the action through GodelianSafetyGovernor
    4. Apply the action to the live MetaLearner (Synthesise phase)
    5. Record the full audit trail so the test can verify causal effect

    Parameters
    ----------
    meta_learner : MetaLearner
        The live learner whose probabilities will be mutated.
    governor : GodelianSafetyGovernor, optional
        Safety governor; a default instance is created if not provided.
    demote_factor : float
        Multiplicative factor for DEMOTE_WORST  (default 0.5 = halve).
    promote_factor : float
        Multiplicative factor for PROMOTE_BEST  (default 2.0 = double).
    boost_factor : float
        Multiplicative factor for BOOST_UPWARD  (default 1.5 = +50%).
    max_upward_rate : float
        Hard ceiling on upward_rate after BOOST_UPWARD.
    acc_drop_threshold : float
        Minimum accuracy drop (vs previous gen) that triggers action.
    """

    def __init__(
        self,
        meta_learner: MetaLearner,
        governor: Optional[GodelianSafetyGovernor] = None,
        demote_factor: float = 0.5,
        promote_factor: float = 2.0,
        boost_factor: float = 1.5,
        max_upward_rate: float = 0.60,
        acc_drop_threshold: float = 0.0,
    ):
        self.meta        = meta_learner
        self.governor    = governor if governor is not None else GodelianSafetyGovernor()
        self.demote_f    = demote_factor
        self.promote_f   = promote_factor
        self.boost_f     = boost_factor
        self.max_upward  = max_upward_rate
        self.drop_thresh = acc_drop_threshold

        self.records: List[SynthesisRecord] = []
        self._pending_record: Optional[SynthesisRecord] = None  # awaiting acc_after

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def synthesise(
        self,
        generation: int,
        acc_this_gen: float,
        acc_prev_gen: Optional[float],
        pattern_summary: Dict[str, Any],
    ) -> SynthesisRecord:
        """
        Run one full synthesis cycle.

        Parameters
        ----------
        generation : int
        acc_this_gen : float
            Accuracy of the generation just completed.
        acc_prev_gen : float or None
            Accuracy of the previous generation (None for gen 0).
        pattern_summary : dict
            Output of MetaCognitionLayer.get_pattern_summary().

        Returns
        -------
        SynthesisRecord
            Full audit record; ``acc_after`` and ``improvement`` are None
            until ``record_next_generation_acc()`` is called.
        """
        before_probs  = self.meta.get_strategy_probabilities()
        before_upward = self.meta.upward_rate

        action, trigger = self._choose_action(
            acc_this_gen, acc_prev_gen, pattern_summary
        )

        # Gate through Gödelian safety
        proposal = self._action_to_proposal(action)
        status, reason = self.governor.evaluate_modification(proposal, verbose=False)

        # Apply only if safe
        applied_action = action
        if status == SafetyStatus.PROVABLY_SAFE:
            self._apply(action)
            logger.info(
                "🔄 CRLS Synthesis gen %d: %s — %s [SAFE]",
                generation, action.value, trigger,
            )
        else:
            applied_action = SynthesisAction.NO_ACTION
            logger.warning(
                "🛡️  CRLS Synthesis gen %d: %s blocked — %s [%s]",
                generation, action.value, reason, status.value,
            )

        after_probs  = self.meta.get_strategy_probabilities()
        after_upward = self.meta.upward_rate

        record = SynthesisRecord(
            generation    = generation,
            action        = applied_action,
            trigger       = trigger,
            before_probs  = before_probs,
            after_probs   = after_probs,
            before_upward = before_upward,
            after_upward  = after_upward,
            safety_status = status.value,
            safety_reason = reason,
            acc_before    = acc_this_gen,
        )
        self.records.append(record)
        self._pending_record = record
        return record

    def record_next_generation_acc(self, acc: float) -> None:
        """
        Fill in acc_after and improvement on the most recent record.

        Call this at the *start* of the generation following a synthesis action.
        """
        if self._pending_record is not None:
            self._pending_record.acc_after  = acc
            self._pending_record.improvement = acc - self._pending_record.acc_before
            logger.info(
                "📊 CRLS causal check gen %d: Δacc = %+.1f%% (%s)",
                self._pending_record.generation,
                self._pending_record.improvement * 100,
                "✅ CONFIRMED" if self._pending_record.causal_confirmed() else "❌ NO IMPROVEMENT",
            )
            self._pending_record = None

    def get_summary(self) -> Dict[str, Any]:
        """Return summary statistics over all synthesis records."""
        if not self.records:
            return {
                "total_syntheses": 0,
                "actions_applied": [],
                "causal_confirmations": 0,
                "causal_confirmation_rate": 0.0,
                "mean_improvement": None,
            }
        applied = [r for r in self.records if r.action != SynthesisAction.NO_ACTION]
        confirmed = [r for r in applied if r.causal_confirmed()]
        improvements = [r.improvement for r in applied if r.improvement is not None]
        return {
            "total_syntheses":         len(self.records),
            "actions_applied":         [r.action.value for r in applied],
            "causal_confirmations":    len(confirmed),
            "causal_confirmation_rate": len(confirmed) / len(applied) if applied else 0.0,
            "mean_improvement":        sum(improvements) / len(improvements) if improvements else None,
            "records":                 [r.to_dict() for r in self.records],
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _choose_action(
        self,
        acc_now: float,
        acc_prev: Optional[float],
        pattern_summary: Dict[str, Any],
    ) -> Tuple[SynthesisAction, str]:
        """
        Rule-based action selection grounded in the failure pattern.

        Priority order:
        1. Cyclical failures → RESET_UNIFORM (escape the attractor)
        2. Declining trend + big drop → DEMOTE_WORST
        3. Declining trend + mild drop → PROMOTE_BEST
        4. Any drop → BOOST_UPWARD (increase plasticity at meta-meta level)
        5. No drop → NO_ACTION
        """
        patterns = pattern_summary.get("detected_patterns", {})
        has_cycle  = any("cyclical" in k for k in patterns)
        drop = (acc_prev - acc_now) if acc_prev is not None else 0.0

        if has_cycle and drop > self.drop_thresh:
            return (
                SynthesisAction.RESET_UNIFORM,
                f"Cyclical failure pattern detected ({list(patterns.keys())}); "
                f"acc dropped {drop:.1%} — resetting to uniform prior",
            )

        if drop > 0.10:
            return (
                SynthesisAction.DEMOTE_WORST,
                f"Large accuracy drop {drop:.1%}; demoting worst strategy",
            )

        if drop > self.drop_thresh:
            return (
                SynthesisAction.PROMOTE_BEST,
                f"Mild accuracy drop {drop:.1%}; promoting best strategy",
            )

        # Upward mutation rate getting stale — only act when accuracy is flat
        # (drop == 0), not when it is already rising (drop < 0).
        if acc_prev is not None and drop == 0 and self.meta.upward_rate < 0.15:
            return (
                SynthesisAction.BOOST_UPWARD,
                "upward_rate low and accuracy flat — boost meta-plasticity",
            )

        return SynthesisAction.NO_ACTION, "accuracy stable — no synthesis required"

    def _action_to_proposal(self, action: SynthesisAction) -> Dict[str, Any]:
        """Map SynthesisAction to a GodelianSafetyGovernor proposal dict."""
        if action == SynthesisAction.DEMOTE_WORST:
            return {"type": "rule_remove",
                    "desc": f"demote worst strategy by factor {self.demote_f}"}
        if action == SynthesisAction.PROMOTE_BEST:
            return {"type": "rule_add",
                    "desc": f"promote best strategy by factor {self.promote_f}"}
        if action == SynthesisAction.RESET_UNIFORM:
            return {"type": "rule_remove",
                    "desc": "reset all strategy weights to uniform prior"}
        if action == SynthesisAction.BOOST_UPWARD:
            new_rate = min(self.max_upward, self.meta.upward_rate * self.boost_f)
            return {"type": "rule_add",
                    "desc": f"boost upward_rate {self.meta.upward_rate:.3f}→{new_rate:.3f}"}
        # NO_ACTION
        return {"type": "rule_add", "desc": "no-op"}

    def _apply(self, action: SynthesisAction) -> None:
        """Execute the synthesis action directly on the MetaLearner."""
        if action == SynthesisAction.NO_ACTION:
            return

        stats       = self.meta.get_statistics()
        best_strat  = stats["best_strategy"]
        worst_strat = min(
            stats["strategy_success_rates"],
            key=stats["strategy_success_rates"].get,
        )

        if action == SynthesisAction.DEMOTE_WORST:
            # Directly multiply worst strategy's probability
            new_p = max(
                self.meta.min_probability,
                self.meta.probabilities[worst_strat] * self.demote_f,
            )
            self.meta.probabilities[worst_strat] = new_p
            self.meta._normalize()
            logger.debug("CRLS: demoted %s → %.4f", worst_strat, new_p)

        elif action == SynthesisAction.PROMOTE_BEST:
            new_p = min(
                self.meta.max_probability,
                self.meta.probabilities[best_strat] * self.promote_f,
            )
            self.meta.probabilities[best_strat] = new_p
            self.meta._normalize()
            logger.debug("CRLS: promoted %s → %.4f", best_strat, new_p)

        elif action == SynthesisAction.RESET_UNIFORM:
            init_p = 1.0 / len(self.meta.strategies)
            for s in self.meta.strategies:
                self.meta.probabilities[s] = init_p
            # Don't reset counters — keep success/failure history
            logger.debug("CRLS: reset to uniform %.4f", init_p)

        elif action == SynthesisAction.BOOST_UPWARD:
            old_rate = self.meta.upward_rate
            self.meta.upward_rate = min(
                self.max_upward,
                old_rate * self.boost_f,
            )
            logger.debug(
                "CRLS: upward_rate %.3f → %.3f",
                old_rate,
                self.meta.upward_rate,
            )


# ---------------------------------------------------------------------------
# GoTacticalCRLS  –  full wiring on real Go puzzles
# ---------------------------------------------------------------------------

class GoTacticalCRLS:
    """
    Complete CRLS Strange Loop wired to 9×9 Go tactical puzzles.

    Combines:
    - MetaLearner (Good's synaptic mutation, *optionally frozen* for causal tests)
    - MetaCognitionLayer (Hofstadter's observer)
    - CRLSSynthesiser (WP17: closes the loop)
    - GodelianSafetyGovernor (gates every synthesis action)

    The design separates two sources of learning:
    - **Autonomous** (MetaLearner upward/downward rates applied per-puzzle)
    - **Synthetic**  (CRLSSynthesiser bulk mutations applied once per generation)

    For causal validation, freeze autonomous updates by setting
    ``upward_rate = downward_rate = 0`` at construction.  Then any
    accuracy improvement must come from the CRLS loop.

    Parameters
    ----------
    strategies : list[str]
        Strategy names (must match the tactic functions in the caller).
    upward_rate, downward_rate : float
        Autonomous MetaLearner rates.  Set to 0.0 for causal test mode.
    synthesiser_kwargs : dict
        Extra kwargs forwarded to CRLSSynthesiser.
    """

    def __init__(
        self,
        strategies: List[str],
        upward_rate: float = 0.20,
        downward_rate: float = 0.15,
        synthesiser_kwargs: Optional[Dict[str, Any]] = None,
    ):
        self.meta     = MetaLearner(
            strategies    = strategies,
            upward_rate   = upward_rate,
            downward_rate = downward_rate,
        )
        self.metacog  = MetaCognitionLayer()
        self.governor = GodelianSafetyGovernor()
        self.synth    = CRLSSynthesiser(
            self.meta,
            governor=self.governor,
            **(synthesiser_kwargs or {}),
        )

        self.generation   = 0
        self.acc_history: List[float] = []
        self.gen_log:     List[Dict]  = []

    # ------------------------------------------------------------------
    # Core generation runner
    # ------------------------------------------------------------------

    def run_generation(
        self,
        puzzles: List[Tuple],  # [(GoBoard, player, correct_move), ...]
        tactic_fns: Dict[str, Callable],
        evaluate_fn: Callable,
    ) -> float:
        """
        Play every puzzle; apply autonomous MetaLearner updates per puzzle.

        Returns accuracy for this generation.
        """
        # Close the causal window from the previous synthesis
        if self.acc_history:
            self.synth.record_next_generation_acc(
                self._evaluate_batch(puzzles, tactic_fns, evaluate_fn, update=False)
            )

        # Now play with updates
        correct = 0
        for i, (board, player, correct_move) in enumerate(puzzles):
            strategy = self.meta.select_strategy()
            move     = tactic_fns[strategy](board, player)

            # Fallback to random if tactic returns nothing legal
            if move is None or not board.is_legal_move(move[0], move[1], player):
                legal = board.get_legal_moves(player)
                move  = legal[0] if legal else (-1, -1)
                strategy = list(tactic_fns.keys())[-1]  # random_legal assumed last

            success = evaluate_fn(board, move, correct_move, player)
            if success:
                self.meta.update_on_success(strategy)
                correct += 1
            else:
                self.meta.update_on_failure(strategy)
                self.metacog.observe_failure(FailureEpisode(
                    turn             = i,
                    failure_type     = FailureType.STRATEGIC_ERROR,
                    context          = {"strategy": strategy, "board_size": board.size},
                    action_taken     = strategy,
                    expected_outcome = 1.0,
                    actual_outcome   = 0.0,
                    causal_diagnosis = f"strategy '{strategy}' failed",
                ))

        acc = correct / len(puzzles)
        self.acc_history.append(acc)
        return acc

    def end_of_generation(self, regime: str = "") -> SynthesisRecord:
        """
        Run the synthesis phase: meta-level observes → synthesiser acts.

        Must be called once per generation *after* run_generation().
        """
        acc_now  = self.acc_history[-1]
        acc_prev = self.acc_history[-2] if len(self.acc_history) >= 2 else None

        record = self.synth.synthesise(
            generation      = self.generation,
            acc_this_gen    = acc_now,
            acc_prev_gen    = acc_prev,
            pattern_summary = self.metacog.get_pattern_summary(),
        )

        self.gen_log.append({
            "generation":   self.generation,
            "regime":       regime,
            "acc":          acc_now,
            "action":       record.action.value,
            "trigger":      record.trigger,
            "safety":       record.safety_status,
            "probs_before": record.before_probs,
            "probs_after":  record.after_probs,
            "upward_rate":  record.after_upward,
        })

        self.generation += 1
        return record

    def get_full_report(self) -> Dict[str, Any]:
        """Return complete experiment report."""
        return {
            "generations":     len(self.acc_history),
            "accuracy_history": self.acc_history,
            "final_accuracy":   self.acc_history[-1] if self.acc_history else None,
            "meta_statistics":  self.meta.get_statistics(),
            "synthesis_summary": self.synth.get_summary(),
            "safety_statistics": self.governor.get_safety_statistics(),
            "generation_log":   self.gen_log,
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _evaluate_batch(
        self,
        puzzles: List[Tuple],
        tactic_fns: Dict[str, Callable],
        evaluate_fn: Callable,
        update: bool = False,
    ) -> float:
        """Evaluate accuracy without synthesis (used for causal window close)."""
        correct = 0
        for board, player, correct_move in puzzles:
            strategy = self.meta.select_strategy()
            move     = tactic_fns[strategy](board, player)
            if move is None or not board.is_legal_move(move[0], move[1], player):
                legal = board.get_legal_moves(player)
                move  = legal[0] if legal else (-1, -1)
                strategy = list(tactic_fns.keys())[-1]
            success = evaluate_fn(board, move, correct_move, player)
            if update:
                if success:
                    self.meta.update_on_success(strategy)
                else:
                    self.meta.update_on_failure(strategy)
            if success:
                correct += 1
        return correct / len(puzzles)


# ---------------------------------------------------------------------------
# Exit-criteria verifier (mirrors v0.114 pattern)
# ---------------------------------------------------------------------------

def verify_wp17_exit_criteria(crls: GoTacticalCRLS) -> Dict[str, bool]:
    """
    Verify WP17 exit criteria.

    Criteria
    --------
    loop_fires         At least one synthesis action was applied
    causal_confirmed   At least one action causally improved accuracy
    within_3_gens      Causal confirmation achieved within first 3 generations
    meta_level_active  MetaCognitionLayer observed at least one failure
    safety_gated       Every synthesis proposal was evaluated by the governor
    no_unsafe_applied  No PROVABLY_UNSAFE action was applied

    Returns
    -------
    dict mapping criterion name → bool
    """
    report = crls.get_full_report()
    synth  = report["synthesis_summary"]
    safety = report["safety_statistics"]

    applied   = [r for r in crls.synth.records
                 if r.action != SynthesisAction.NO_ACTION]
    confirmed = [r for r in applied if r.causal_confirmed()]

    # Earliest generation with a confirmed causal improvement
    first_confirm_gen = (
        min(r.generation for r in confirmed) if confirmed else None
    )

    criteria = {
        "loop_fires":        len(applied) > 0,
        "causal_confirmed":  len(confirmed) > 0,
        "within_3_gens":     (first_confirm_gen is not None
                              and first_confirm_gen <= 2),
        "meta_level_active": (report["meta_statistics"]["attempt_count"] > 0
                              and len(crls.metacog.failure_history) > 0),
        "safety_gated":      safety["total_decisions"] > 0,
        "no_unsafe_applied": all(
            r.safety_status != SafetyStatus.PROVABLY_UNSAFE.value
            for r in crls.synth.records
            if r.action != SynthesisAction.NO_ACTION
        ),
    }

    logger.info("WP17 exit criteria: %s", criteria)
    return criteria
