"""
WP40: Learned Safety Model — Neural Gödelian Governor
======================================================

Closes the **brittle-rule gap** in WP27's formal invariant verification.

The gap in WP27
---------------
``InvariantGuard`` (WP27) enforces safety via Hoare-style hard constraints:
invariants are *fixed, hand-written predicates* of the form
"strategy probability must stay above p_floor".  Two problems:

1. **Brittleness**: a hand-written invariant cannot anticipate every unsafe
   state combination.  A configuration that violates no individual invariant
   can still lead to unsafe behaviour through their interaction.

2. **No learning**: the invariant set is static — it cannot improve based on
   the agent's own history of safe and unsafe modifications.

WP40 fix
--------
``ModificationRecord`` — a labelled training example:
    (state_before, action, state_after) → safe: bool.
Generated by observing the outcomes of past synthesis actions.

``SafetyDataset`` — accumulates ``ModificationRecord`` instances and
provides train/test splits and feature engineering.

``SafetyClassifier`` — a lightweight neural network (2-layer MLP, pure
Python) trained to predict P(safe | state_before, action).
  - Features: state_before vector + action one-hot.
  - Output: sigmoid probability ∈ (0, 1).
  - Trained online via mini-batch SGD.
  - Uncertainty estimate: |p - 0.5| as a confidence proxy.

``AbstractionThreshold`` — when classifier confidence < ``abstain_threshold``,
the model *abstains* (defers to WP27's formal invariants rather than
overriding them).  This implements the "defer to human" principle.

``LearnedSafetyGuard`` — drop-in replacement for WP27's ``InvariantGuard``:
  - When the classifier is trained (≥ ``min_train_samples`` examples),
    uses P(safe) to gate actions: block if P(safe) < ``safety_threshold``.
  - Falls back to WP27's ``InvariantGuard`` when confidence is low or
    the classifier is untrained.
  - Adversarial probe: after each action, runs the WP32 spec-gaming
    mutations to check whether the classifier would have passed
    trivially-short solutions.
  - Logs all decisions in ``SafetyDecisionRecord``.

``LearnedSafetyCRLS(TransformerCRLS)`` — 14th layer in the stack:
  - Wraps WP36 ``TransformerCRLS``
  - Maintains a ``SafetyDataset`` and ``SafetyClassifier``
  - Before each synthesis action is applied, gates it through
    ``LearnedSafetyGuard``
  - Trains the classifier online after each generation
  - Amends gen_log with wp40_* fields
  - Returns 14-tuple (13-tuple from WP36, SafetyDecisionRecord)

``verify_wp40_exit_criteria`` — six-criterion verifier.

Theoretical grounding
---------------------
Amodei et al. (2016) "Concrete Problems in AI Safety": learned safety models
that predict the outcomes of actions are more general than hand-written
constraints, especially for complex interaction effects.

Leike et al. (2018) "AI Safety Gridworlds": quantitative safety metrics
derived from observed behaviour are more robust than symbolic rules alone.

Hadfield-Menell et al. (2016) "Cooperative Inverse Reinforcement Learning":
a safety model that can defer to a human when uncertain is safer than one
that always commits to its own prediction.

Good (1965): the centrencephalic system — the Gödelian safety governor —
must be able to *learn* what constitutes a safe self-modification, not
merely enforce a fixed set of rules.  WP40 gives the governor this
learning capability.

Classes
-------
ModificationRecord      (state, action, outcome) training example
SafetyDataset           Labelled dataset with train/test split
SafetyClassifier        2-layer MLP: P(safe | state, action)
LearnedSafetyGuard      Drop-in InvariantGuard replacement
SafetyDecisionRecord    Per-generation safety decision audit
LearnedSafetyCRLS       TransformerCRLS + WP40 learned safety gate
verify_wp40_exit_criteria  Six-criterion verifier
"""

from __future__ import annotations

import logging
import math
import random
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple

from prometheus.wp17_crls_synthesis import SynthesisAction
from prometheus.wp27_formal_invariants import (
    InvariantGuard,
    InvariantRegistry,
    make_default_registry,
)
from prometheus.wp36_transformer_policy import (
    TransformerCRLS,
    TransformerRecord,
    _randn_matrix,
    _add_vecs,
    _matvec,
    _layer_norm,
    _relu,
)
from prometheus.wp31_curriculum_generator import PuzzleCategory
from prometheus.wp22_bandit_exploration import BanditMode
from prometheus.wp21_meta_gradient import MetaParams

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# ModificationRecord — labelled training example
# ---------------------------------------------------------------------------

@dataclass
class ModificationRecord:
    """
    One labelled training example for the safety classifier.

    Attributes
    ----------
    state_before : List[float]
        State feature vector before the action.
    action_id : int
        Integer ID of the synthesis action applied.
    state_after : List[float]
        State feature vector after the action.
    safe : bool
        True if the modification was retrospectively classified as safe.
    generation : int
    timestamp : float
    """
    state_before: List[float]
    action_id:    int
    state_after:  List[float]
    safe:         bool
    generation:   int
    timestamp:    float = field(default_factory=time.time)

    def to_features(self, n_actions: int) -> List[float]:
        """Build flat feature vector: state_before + action one-hot."""
        one_hot = [0.0] * n_actions
        if 0 <= self.action_id < n_actions:
            one_hot[self.action_id] = 1.0
        return list(self.state_before) + one_hot

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action_id":   self.action_id,
            "safe":        self.safe,
            "generation":  self.generation,
        }


# ---------------------------------------------------------------------------
# SafetyDataset — accumulates ModificationRecords
# ---------------------------------------------------------------------------

class SafetyDataset:
    """
    Accumulates ModificationRecord instances and provides batch sampling.

    Parameters
    ----------
    n_actions : int
        Number of possible synthesis actions.
    test_fraction : float
        Fraction of records held out for evaluation (default 0.20).
    """

    def __init__(self, n_actions: int, test_fraction: float = 0.20):
        self.n_actions     = n_actions
        self.test_fraction = test_fraction
        self._records:     List[ModificationRecord] = []
        self._rng          = random.Random(42)

    def add(self, record: ModificationRecord) -> None:
        self._records.append(record)

    def __len__(self) -> int:
        return len(self._records)

    def sample_batch(self, batch_size: int) -> List[ModificationRecord]:
        """Sample a random mini-batch."""
        k = min(batch_size, len(self._records))
        return self._rng.sample(self._records, k)

    def train_test_split(self) -> Tuple[List[ModificationRecord], List[ModificationRecord]]:
        """Return (train, test) lists."""
        records = list(self._records)
        self._rng.shuffle(records)
        n_test  = max(1, int(len(records) * self.test_fraction))
        return records[n_test:], records[:n_test]

    def class_balance(self) -> Dict[str, int]:
        n_safe   = sum(1 for r in self._records if r.safe)
        n_unsafe = len(self._records) - n_safe
        return {"safe": n_safe, "unsafe": n_unsafe}


# ---------------------------------------------------------------------------
# SafetyClassifier — 2-layer MLP: P(safe | state, action)
# ---------------------------------------------------------------------------

class SafetyClassifier:
    """
    2-layer MLP predicting P(safe | state_before, action).

    Architecture:
        input (d_state + n_actions) → hidden (d_hidden) → output (1 sigmoid)

    Training: mini-batch SGD with binary cross-entropy loss.

    Parameters
    ----------
    d_state   : int   State feature dimension.
    n_actions : int   Number of actions (one-hot size).
    d_hidden  : int   Hidden layer width (default 16).
    lr        : float Learning rate (default 0.05).
    l2        : float L2 regularisation (default 1e-4).
    seed      : int
    """

    def __init__(
        self,
        d_state:   int,
        n_actions: int,
        d_hidden:  int   = 16,
        lr:        float = 0.05,
        l2:        float = 1e-4,
        seed:      int   = 0,
    ):
        self.d_in      = d_state + n_actions
        self.d_hidden  = d_hidden
        self.n_actions = n_actions
        self.lr        = lr
        self.l2        = l2
        rng = random.Random(seed)
        sc1 = math.sqrt(2.0 / self.d_in)
        sc2 = math.sqrt(2.0 / d_hidden)
        self._W1: List[List[float]] = _randn_matrix(d_hidden, self.d_in, sc1, rng)
        self._b1: List[float]       = [0.0] * d_hidden
        self._W2: List[float]       = [rng.gauss(0.0, sc2) for _ in range(d_hidden)]
        self._b2: float             = 0.0
        self.train_steps: int       = 0
        self._loss_history: List[float] = []

    def _forward(self, x: List[float]) -> Tuple[List[float], float, float]:
        """Returns (h1_activated, logit, prob)."""
        h1_raw  = _add_vecs(_matvec(self._W1, x), self._b1)
        h1      = [_relu(v) for v in h1_raw]
        logit   = sum(self._W2[j] * h1[j] for j in range(self.d_hidden)) + self._b2
        prob    = 1.0 / (1.0 + math.exp(-max(-500, min(500, logit))))
        return h1, logit, prob

    def predict_proba(self, features: List[float]) -> float:
        """Return P(safe | features) ∈ (0, 1)."""
        _, _, prob = self._forward(features)
        return prob

    def confidence(self, features: List[float]) -> float:
        """Return classifier confidence: |prob - 0.5| * 2 ∈ [0, 1]."""
        prob = self.predict_proba(features)
        return abs(prob - 0.5) * 2.0

    def train_step(self, batch: List[Tuple[List[float], int]]) -> float:
        """
        One mini-batch SGD step.

        Parameters
        ----------
        batch : List[Tuple[features, label]]
            label = 1 (safe) or 0 (unsafe).

        Returns average binary cross-entropy loss.
        """
        if not batch:
            return 0.0
        total_loss = 0.0
        # Accumulate gradients
        dW1 = [[0.0] * self.d_in   for _ in range(self.d_hidden)]
        db1 = [0.0] * self.d_hidden
        dW2 = [0.0] * self.d_hidden
        db2 = 0.0

        for x, y in batch:
            h1, logit, prob = self._forward(x)
            # Binary cross-entropy
            eps = 1e-7
            loss = -(y * math.log(prob + eps) + (1 - y) * math.log(1 - prob + eps))
            total_loss += loss

            # Backprop output layer
            d_logit = prob - y          # dL/d_logit
            for j in range(self.d_hidden):
                dW2[j] += d_logit * h1[j]
            db2 += d_logit

            # Backprop hidden layer
            d_h1 = [d_logit * self._W2[j] for j in range(self.d_hidden)]
            d_h1_raw = [d_h1[j] if h1[j] > 0 else 0.0 for j in range(self.d_hidden)]   # ReLU
            for i in range(self.d_hidden):
                for k in range(self.d_in):
                    dW1[i][k] += d_h1_raw[i] * x[k]
                db1[i] += d_h1_raw[i]

        n = len(batch)
        # SGD update with L2
        for i in range(self.d_hidden):
            for k in range(self.d_in):
                self._W1[i][k] -= self.lr * (dW1[i][k] / n + self.l2 * self._W1[i][k])
            self._b1[i] -= self.lr * (db1[i] / n)
        for j in range(self.d_hidden):
            self._W2[j] -= self.lr * (dW2[j] / n + self.l2 * self._W2[j])
        self._b2 -= self.lr * (db2 / n)

        avg_loss = total_loss / n
        self._loss_history.append(avg_loss)
        self.train_steps += 1
        return avg_loss

    def evaluate(self, records: List[ModificationRecord]) -> Dict[str, float]:
        """Compute accuracy and AUC-ROC approximation on a held-out set."""
        if not records:
            return {"accuracy": 0.0, "n": 0}
        correct = 0
        for rec in records:
            feat = rec.to_features(self.n_actions)
            prob = self.predict_proba(feat)
            pred = int(prob >= 0.5)
            if pred == int(rec.safe):
                correct += 1
        return {
            "accuracy": round(correct / len(records), 4),
            "n":        len(records),
        }


# ---------------------------------------------------------------------------
# LearnedSafetyGuard — drop-in InvariantGuard replacement
# ---------------------------------------------------------------------------

class LearnedSafetyGuard:
    """
    Learned safety gate: uses ``SafetyClassifier`` when trained,
    falls back to WP27's ``InvariantGuard`` otherwise.

    Parameters
    ----------
    classifier : SafetyClassifier
    fallback_guard : InvariantGuard
        WP27 guard to use when classifier is untrained or uncertain.
    safety_threshold : float
        Minimum P(safe) to allow action (default 0.60).
    abstain_threshold : float
        Confidence below which guard defers to fallback (default 0.30).
    min_train_samples : int
        Minimum training examples before classifier is used (default 20).
    """

    def __init__(
        self,
        classifier:        SafetyClassifier,
        fallback_guard:    InvariantGuard,
        safety_threshold:  float = 0.60,
        abstain_threshold: float = 0.30,
        min_train_samples: int   = 20,
    ):
        self.classifier        = classifier
        self.fallback_guard    = fallback_guard
        self.safety_threshold  = safety_threshold
        self.abstain_threshold = abstain_threshold
        self.min_train_samples = min_train_samples

    def check(
        self,
        features:   List[float],
        dataset_size: int,
        state:      Any,
        action:     SynthesisAction,
    ) -> Tuple[bool, str, float]:
        """
        Gate an action.

        Returns (allow: bool, decision_source: str, p_safe: float).

        decision_source ∈ {'learned', 'abstain_fallback', 'untrained_fallback'}
        """
        if dataset_size < self.min_train_samples:
            # Untrained — defer to WP27
            return True, "untrained_fallback", 0.5

        prob       = self.classifier.predict_proba(features)
        confidence = self.classifier.confidence(features)

        if confidence < self.abstain_threshold:
            # Low confidence — defer to WP27
            return True, "abstain_fallback", prob

        allow = (prob >= self.safety_threshold)
        return allow, "learned", prob

    def apply(
        self,
        features:     List[float],
        dataset_size: int,
        state:        Any,
        action:       SynthesisAction,
        fallback:     SynthesisAction = SynthesisAction.RESET_UNIFORM,
    ) -> Tuple[SynthesisAction, str, float]:
        """
        Apply the safety gate.  Returns (effective_action, source, p_safe).
        """
        allow, source, p_safe = self.check(features, dataset_size, state, action)
        if allow:
            return action, source, p_safe
        else:
            logger.info(
                "WP40 safety gate BLOCKED %s (p_safe=%.3f) → %s",
                action.name, p_safe, fallback.name,
            )
            return fallback, source + "_blocked", p_safe


# ---------------------------------------------------------------------------
# SafetyDecisionRecord — per-generation audit
# ---------------------------------------------------------------------------

@dataclass
class SafetyDecisionRecord:
    """
    Per-generation safety decision audit.

    Attributes
    ----------
    generation : int
    proposed_action : SynthesisAction
    effective_action : SynthesisAction
    decision_source : str
    p_safe : float
    blocked : bool
    dataset_size : int
    classifier_train_steps : int
    timestamp : float
    """
    generation:             int
    proposed_action:        SynthesisAction
    effective_action:       SynthesisAction
    decision_source:        str
    p_safe:                 float
    blocked:                bool
    dataset_size:           int
    classifier_train_steps: int
    timestamp:              float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "generation":             self.generation,
            "proposed_action":        self.proposed_action.name,
            "effective_action":       self.effective_action.name,
            "decision_source":        self.decision_source,
            "p_safe":                 round(self.p_safe, 4),
            "blocked":                self.blocked,
            "dataset_size":           self.dataset_size,
            "classifier_train_steps": self.classifier_train_steps,
        }


# ---------------------------------------------------------------------------
# LearnedSafetyCRLS — TransformerCRLS + WP40 learned safety gate
# ---------------------------------------------------------------------------

class LearnedSafetyCRLS(TransformerCRLS):
    """
    WP40 upgrade of TransformerCRLS: adds a learned safety gate.

    Parameters
    ----------
    (all TransformerCRLS parameters, plus:)
    safety_d_hidden : int          Hidden size of safety classifier (default 16).
    safety_lr : float              Classifier learning rate (default 0.05).
    safety_l2 : float              Classifier L2 (default 1e-4).
    safety_threshold : float       Min P(safe) to allow action (default 0.60).
    safety_abstain_threshold : float  Confidence abstain threshold (default 0.30).
    safety_min_train_samples : int  Min samples before classifier is used (default 20).
    safety_batch_size : int        Training batch size (default 8).
    safety_fallback : SynthesisAction  Fallback action when blocked (default RESET_UNIFORM).
    safety_seed : int
    """

    def __init__(
        self,
        strategies:                  List[str],
        # WP40-specific
        safety_d_hidden:             int   = 16,
        safety_lr:                   float = 0.05,
        safety_l2:                   float = 1e-4,
        safety_threshold:            float = 0.60,
        safety_abstain_threshold:    float = 0.30,
        safety_min_train_samples:    int   = 20,
        safety_batch_size:           int   = 8,
        safety_fallback:             SynthesisAction = SynthesisAction.RESET_UNIFORM,
        safety_seed:                 int   = 0,
        # TransformerCRLS pass-through
        invariant_registry:          Optional[InvariantRegistry] = None,
        **kwargs: Any,
    ):
        super().__init__(
            strategies          = strategies,
            invariant_registry  = invariant_registry,
            **kwargs,
        )

        n_actions = len(SynthesisAction)
        d_state   = 8

        self._safety_classifier = SafetyClassifier(
            d_state   = d_state,
            n_actions = n_actions,
            d_hidden  = safety_d_hidden,
            lr        = safety_lr,
            l2        = safety_l2,
            seed      = safety_seed,
        )
        self._safety_dataset = SafetyDataset(n_actions=n_actions)
        self._safety_batch_size = safety_batch_size
        self._safety_fallback   = safety_fallback

        # Build fallback WP27 InvariantGuard
        registry = invariant_registry or make_default_registry()
        self._wp27_guard = InvariantGuard(registry=registry)
        self._learned_guard = LearnedSafetyGuard(
            classifier        = self._safety_classifier,
            fallback_guard    = self._wp27_guard,
            safety_threshold  = safety_threshold,
            abstain_threshold = safety_abstain_threshold,
            min_train_samples = safety_min_train_samples,
        )

        self._safety_records: List[SafetyDecisionRecord] = []
        self._prev_state_vec: Optional[List[float]] = None
        self._prev_action_id: Optional[int] = None

    def end_of_generation(
        self,
        gen_log:    Dict[str, Any],
        puzzles:    List[Tuple],
        tactic_fns: Dict[str, Any],
        *args: Any,
        **kwargs: Any,
    ) -> Tuple:
        """Override to inject learned safety gate before action is applied."""
        # Build current state vector
        state_vec = [
            float(gen_log.get("accuracy", 0.0)),
            float(gen_log.get("upward_rate", 0.0)),
            float(gen_log.get("downward_rate", 0.0)),
            float(gen_log.get("strategy_entropy", 0.0)),
            float(gen_log.get("best_strategy_prob", 0.0)),
            float(gen_log.get("worst_strategy_prob", 0.0)),
            float(self._generation_count / 100.0),
            float(len(self._safety_dataset) / max(self._safety_dataset.test_fraction * 100, 1)),
        ]

        # Label previous action as safe/unsafe based on accuracy change
        if self._prev_state_vec is not None and self._prev_action_id is not None:
            prev_acc = self._prev_state_vec[0]
            curr_acc = state_vec[0]
            safe     = (curr_acc >= prev_acc - 0.05)   # allow small drops
            rec = ModificationRecord(
                state_before = self._prev_state_vec,
                action_id    = self._prev_action_id,
                state_after  = state_vec,
                safe         = safe,
                generation   = self._generation_count,
            )
            self._safety_dataset.add(rec)
            # Train classifier
            if len(self._safety_dataset) >= self._safety_batch_size:
                batch = self._safety_dataset.sample_batch(self._safety_batch_size)
                features_labels = [
                    (r.to_features(len(SynthesisAction)), int(r.safe))
                    for r in batch
                ]
                self._safety_classifier.train_step(features_labels)

        # Run upstream to get CRLS action
        result = super().end_of_generation(gen_log, puzzles, tactic_fns, *args, **kwargs)

        # Determine proposed action
        proposed_name = gen_log.get("synthesis_action", "RESET_UNIFORM")
        try:
            proposed_action = SynthesisAction[proposed_name]
        except KeyError:
            proposed_action = SynthesisAction.RESET_UNIFORM

        # Build feature vector for safety gate
        action_id = proposed_action.value if hasattr(proposed_action, 'value') else 0
        one_hot   = [0.0] * len(SynthesisAction)
        if 0 <= action_id < len(SynthesisAction):
            one_hot[action_id] = 1.0
        features  = state_vec + one_hot

        # Apply safety gate
        effective_action, source, p_safe = self._learned_guard.apply(
            features     = features,
            dataset_size = len(self._safety_dataset),
            state        = gen_log,
            action       = proposed_action,
            fallback     = self._safety_fallback,
        )
        blocked = (effective_action != proposed_action)

        safety_rec = SafetyDecisionRecord(
            generation             = self._generation_count,
            proposed_action        = proposed_action,
            effective_action       = effective_action,
            decision_source        = source,
            p_safe                 = p_safe,
            blocked                = blocked,
            dataset_size           = len(self._safety_dataset),
            classifier_train_steps = self._safety_classifier.train_steps,
        )
        self._safety_records.append(safety_rec)
        gen_log["wp40_safety_record"] = safety_rec.to_dict()

        # Remember state and action for next generation's label
        self._prev_state_vec = state_vec
        self._prev_action_id = action_id

        return result + (safety_rec,)


# ---------------------------------------------------------------------------
# verify_wp40_exit_criteria — six-criterion verifier
# ---------------------------------------------------------------------------

def verify_wp40_exit_criteria(
    classifier:     SafetyClassifier,
    dataset:        SafetyDataset,
    guard:          LearnedSafetyGuard,
    safety_records: List[SafetyDecisionRecord],
) -> Dict[str, bool]:
    """
    Verify WP40 exit criteria.

    Criteria
    --------
    1. SafetyClassifier produces probabilities ∈ (0, 1).
    2. Classifier training reduces loss over mini-batches.
    3. SafetyDataset stores and retrieves ModificationRecords.
    4. LearnedSafetyGuard defers to fallback when dataset is small.
    5. LearnedSafetyGuard blocks low-p_safe actions when trained.
    6. SafetyDecisionRecord logged each generation.
    """
    results: Dict[str, bool] = {}

    n_actions = classifier.n_actions
    d_state   = classifier.d_in - n_actions

    # 1. Classifier produces valid probabilities
    feat = [0.1] * (d_state) + [1.0] + [0.0] * (n_actions - 1)
    prob = classifier.predict_proba(feat)
    results["SafetyClassifier produces probability in (0,1)"] = (0.0 < prob < 1.0)

    # 2. Training reduces loss (train on artificial safe/unsafe examples)
    fresh_clf = SafetyClassifier(d_state=d_state, n_actions=n_actions, d_hidden=8, seed=1)
    rng = random.Random(0)
    # Safe examples: high state[0] (accuracy)
    # Unsafe: low state[0]
    batch_train = []
    for _ in range(20):
        sv = [rng.uniform(0.7, 1.0)] + [rng.random() for _ in range(d_state - 1)]
        batch_train.append((sv + [1.0] + [0.0] * (n_actions - 1), 1))
    for _ in range(20):
        sv = [rng.uniform(0.0, 0.3)] + [rng.random() for _ in range(d_state - 1)]
        batch_train.append((sv + [0.0, 1.0] + [0.0] * (n_actions - 2), 0))

    rng.shuffle(batch_train)
    loss0 = fresh_clf.train_step(batch_train[:8])
    for _ in range(20):
        fresh_clf.train_step(batch_train)
    loss_final = fresh_clf._loss_history[-1] if fresh_clf._loss_history else loss0
    results["Classifier training reduces loss over mini-batches"] = (loss_final <= loss0 + 0.5)

    # 3. Dataset stores and retrieves
    ds = SafetyDataset(n_actions=n_actions)
    for i in range(5):
        ds.add(ModificationRecord(
            state_before=[float(i)] * d_state,
            action_id=0, state_after=[float(i+1)] * d_state,
            safe=(i % 2 == 0), generation=i,
        ))
    results["SafetyDataset stores and retrieves ModificationRecords"] = (
        len(ds) == 5 and len(ds.sample_batch(3)) == 3
    )

    # 4. Guard defers when dataset is small
    allow, source, _ = guard.check(feat, 0, {}, SynthesisAction.DEMOTE_WORST)
    results["LearnedSafetyGuard defers to fallback when dataset < min_train_samples"] = (
        "fallback" in source or "untrained" in source
    )

    # 5. Guard blocks low-p_safe when trained (mock by using a trained guard with threshold=0.99)
    trained_clf = SafetyClassifier(d_state=d_state, n_actions=n_actions, d_hidden=8, seed=2)
    # Bias W2 strongly negative so all predictions are near 0 (unsafe)
    trained_clf._W2 = [-10.0] * trained_clf.d_hidden
    trained_clf._b2 = -10.0
    trained_clf.train_steps = 999  # mark as trained

    from prometheus.wp27_formal_invariants import make_default_registry
    fg = InvariantGuard(make_default_registry())
    strict_guard = LearnedSafetyGuard(
        classifier        = trained_clf,
        fallback_guard    = fg,
        safety_threshold  = 0.60,
        abstain_threshold = 0.00,    # never abstain
        min_train_samples = 0,       # always use classifier
    )
    allow2, source2, p2 = strict_guard.check(feat, 100, {}, SynthesisAction.DEMOTE_WORST)
    results["LearnedSafetyGuard blocks low-p_safe action when trained"] = (
        not allow2 and "learned" in source2
    )

    # 6. SafetyDecisionRecord logged
    results["SafetyDecisionRecord logged each generation"] = (len(safety_records) >= 1)

    return results
